### ISSUE TITLE
Site.Wrapper / Site.Nav misaligned collapsed menu

### ISSUE THREAD

**Issue by jdelrosarioo** [tabler/tabler-react#302]
Using original tabler, the nav looks like this --

![image](https://user-images.githubusercontent.com/40348356/45071323-31e8df80-b108-11e8-9408-a8b666233bba.png)

But using the component, the nav looks messed --

![image](https://user-images.githubusercontent.com/40348356/45071340-49c06380-b108-11e8-8e18-e7af45a26317.png)

Looking at the Grid.Col class, the css class "col" is always included causing the particular issue

```css
const classes = cn(
    {
      col: true,
      [`col-${width}`]: width,
      [`col-xs-${xs}`]: xs,
      [`col-xs-auto`]: xsAuto,
      [`col-sm-${sm}`]: sm,
      [`col-sm-auto`]: smAuto,
      [`col-md-${md}`]: md,
      [`col-md-auto`]: mdAuto,
      [`col-lg-${lg}`]: lg,
      [`col-lg-auto`]: lgAuto,
      [`col-xl-${xl}`]: xl,
      [`col-xl-auto`]: xlAuto,
      "col-auto": auto,
      [`offset-${offset}`]: offset,
      [`offset-xs-${offsetXs}`]: offsetXs,
      [`offset-sm-${offsetSm}`]: offsetSm,
      [`offset-md-${offsetMd}`]: offsetMd,
      [`offset-lg-${offsetLg}`]: offsetLg,
      [`offset-xl-${offsetXl}`]: offsetXl,
    },
    className
  );
```
