### ISSUE TITLE
Container

### ISSUE THREAD

**Issue by gdg87** [tabler/tabler-react#369]
How can I use the "container-fluid" bootstrap class instead of  "container"?

**Comment by zabaala** [comment]
I had to do the same thing. This work for me: 

```css
.container {
    max-width: 100%;
}
```
